EVENT_TYPE = [
    "Movement.Transport",
    "Personnel.Elect",
    "Personnel.Start-Position",
    "Personnel.Nominate",
    "Personnel.End-Position",
    "Conflict.Attack",
    "Conflict.Demonstrate",
    "Contact.Phone-Write",
    "Contact.Meet",
    "Transaction.Transfer-Money",
    "Transaction.Transfer-Ownership",
    "Business.Start-Org",
    "Business.Merge-Org",
    "Business.Declare-Bankruptcy",
    "Business.End-Org",
    "Life.Be-Born",
    "Life.Injure",
    "Life.Die",
    "Life.Marry",
    "Life.Divorce",
    "Justice.Sue",
    "Justice.Arrest-Jail",
    "Justice.Execute",
    "Justice.Charge-Indict",
    "Justice.Convict",
    "Justice.Trial-Hearing",
    "Justice.Sentence",
    "Justice.Release-Parole",
    "Justice.Fine",
    "Justice.Pardon",
    "Justice.Appeal",
    "Justice.Extradite",
    "Justice.Acquit"
]

ENTITY = ['PER', 'ORG', 'GPE', 'LOC', 'FAC', 'VEH', 'WEA']

ROLE = ['Org', 'Place', 'Instrument', 'Vehicle', 'Attacker', 'Prosecutor', 'Agent', 'Victim', 'Origin', 'Target', 'Giver', 'Seller', 'Defendant', 'Recipient', 'Entity', 'Plaintiff', 'Person', 'Artifact', 'Destination', 'Adjudicator', 'Beneficiary', 'Buyer']


All_Valid_EntTypes = {
    ('Movement.Transport', 'Vehicle'): {'VEH'}, 
    ('Movement.Transport', 'Artifact'): {'VEH', 'PER', 'WEA'}, 
    ('Movement.Transport', 'Destination'): {'GPE', 'FAC', 'LOC'}, 
    ('Personnel.Elect', 'Person'): {'PER'}, 
    ('Movement.Transport', 'Agent'): {'ORG', 'GPE', 'PER'}, 
    ('Personnel.Start-Position', 'Person'): {'PER'}, 
    ('Personnel.Start-Position', 'Entity'): {'ORG', 'GPE'}, 
    ('Personnel.Nominate', 'Person'): {'PER'}, 
    ('Conflict.Attack', 'Place'): {'GPE', 'FAC', 'LOC'}, 
    ('Personnel.End-Position', 'Entity'): {'ORG', 'GPE'}, 
    ('Personnel.End-Position', 'Person'): {'PER'}, 
    ('Contact.Meet', 'Entity'): {'ORG', 'GPE', 'PER'}, 
    ('Contact.Meet', 'Place'): {'GPE', 'FAC', 'LOC'}, 
    ('Life.Marry', 'Person'): {'PER'}, 
    ('Personnel.Elect', 'Entity'): {'ORG', 'GPE', 'PER'}, 
    ('Conflict.Attack', 'Target'): {'ORG', 'PER', 'VEH', 'FAC', 'LOC', 'WEA'}, 
    ('Conflict.Attack', 'Attacker'): {'ORG', 'GPE', 'PER'}, 
    ('Transaction.Transfer-Money', 'Giver'): {'ORG', 'GPE', 'PER'},
    ('Transaction.Transfer-Money', 'Recipient'): {'ORG', 'GPE', 'PER'}, 
    ('Conflict.Demonstrate', 'Entity'): {'ORG', 'PER'}, 
    ('Conflict.Demonstrate', 'Place'): {'GPE', 'FAC', 'LOC'}, 
    ('Business.End-Org', 'Place'): {'GPE', 'FAC'}, 
    ('Justice.Sue', 'Plaintiff'): {'ORG', 'PER'}, 
    ('Life.Injure', 'Victim'): {'PER'}, 
    ('Life.Injure', 'Agent'): {'GPE', 'PER'}, 
    ('Life.Die', 'Victim'): {'PER'}, 
    ('Life.Die', 'Agent'): {'ORG', 'GPE', 'PER'}, 
    ('Personnel.Start-Position', 'Place'): {'GPE', 'FAC'}, 
    ('Life.Divorce', 'Place'): {'GPE', 'FAC', 'LOC'},
    ('Life.Die', 'Place'): {'GPE', 'FAC', 'LOC'}, 
    ('Justice.Arrest-Jail', 'Person'): {'PER'}, 
    ('Justice.Arrest-Jail', 'Agent'): {'ORG', 'GPE', 'PER'}, 
    ('Personnel.End-Position', 'Place'): {'GPE', 'FAC'}, 
    ('Contact.Phone-Write', 'Entity'): {'ORG', 'PER'}, ('Life.Injure', 'Place'): {'GPE', 'FAC', 'LOC'}, ('Transaction.Transfer-Ownership', 'Buyer'): {'ORG', 'GPE', 'PER'}, ('Transaction.Transfer-Ownership', 'Artifact'): {'ORG', 'VEH', 'FAC', 'WEA'}, ('Transaction.Transfer-Ownership', 'Seller'): {'ORG', 'GPE', 'PER'}, ('Conflict.Attack', 'Instrument'): {'VEH', 'WEA'}, ('Life.Die', 'Instrument'): {'VEH', 'WEA'}, ('Justice.Arrest-Jail', 'Place'): {'GPE', 'FAC'}, ('Movement.Transport', 'Origin'): {'GPE', 'FAC', 'LOC'}, ('Business.End-Org', 'Org'): {'ORG'}, ('Life.Injure', 'Instrument'): {'VEH', 'WEA'}, ('Transaction.Transfer-Ownership', 'Place'): {'GPE', 'FAC', 'LOC'}, ('Transaction.Transfer-Ownership', 'Beneficiary'): {'GPE', 'PER'}, ('Justice.Execute', 'Place'): {'GPE', 'FAC'}, ('Justice.Execute', 'Agent'): {'ORG', 'GPE', 'PER'}, ('Conflict.Attack', 'Victim'): {'PER'}, ('Contact.Phone-Write', 'Place'): {'GPE', 'FAC', 'LOC'}, ('Justice.Trial-Hearing', 'Defendant'): {'ORG', 'PER'}, ('Justice.Execute', 'Person'): {'PER'}, ('Movement.Transport', 'Place'): {'GPE'}, ('Personnel.Elect', 'Place'): {'GPE', 'LOC'}, ('Life.Be-Born', 'Place'): {'GPE', 'FAC', 'LOC'}, ('Justice.Charge-Indict', 'Adjudicator'): {'ORG', 'PER'}, ('Business.Start-Org', 'Org'): {'ORG'}, ('Business.Start-Org', 'Place'): {'GPE', 'FAC'}, ('Justice.Convict', 'Defendant'): {'ORG', 'PER'}, ('Justice.Convict', 'Adjudicator'): {'ORG'}, ('Justice.Sentence', 'Defendant'): {'ORG', 'PER'}, ('Justice.Sentence', 'Adjudicator'): {'ORG', 'GPE', 'PER'}, ('Business.Declare-Bankruptcy', 'Org'): {'ORG', 'PER'}, ('Justice.Release-Parole', 'Entity'): {'ORG', 'GPE', 'PER'}, ('Justice.Release-Parole', 'Person'): {'PER'}, ('Justice.Charge-Indict', 'Defendant'): {'ORG', 'PER'}, ('Justice.Trial-Hearing', 'Place'): {'GPE', 'FAC', 'LOC'}, ('Justice.Trial-Hearing', 'Adjudicator'): {'ORG', 'PER'}, ('Justice.Trial-Hearing', 'Prosecutor'): {'ORG', 'PER'}, ('Justice.Charge-Indict', 'Prosecutor'): {'ORG', 'GPE', 'PER'}, ('Justice.Fine', 'Entity'): {'ORG', 'GPE', 'PER'}, ('Business.Start-Org', 'Agent'): {'ORG', 'GPE', 'PER'}, ('Justice.Pardon', 'Adjudicator'): {'ORG', 'PER'}, ('Justice.Charge-Indict', 'Place'): {'GPE', 'FAC', 'LOC'}, ('Justice.Appeal', 'Adjudicator'): {'ORG', 'PER'}, ('Justice.Appeal', 'Plaintiff'): {'ORG', 'GPE', 'PER'}, ('Justice.Sentence', 'Place'): {'GPE', 'FAC'}, ('Life.Die', 'Person'): {'PER'}, ('Life.Be-Born', 'Person'): {'PER'}, ('Justice.Release-Parole', 'Place'): {'GPE', 'FAC'}, ('Justice.Sue', 'Defendant'): {'ORG', 'GPE', 'PER'}, ('Transaction.Transfer-Money', 'Beneficiary'): {'ORG', 'GPE', 'PER'}, ('Justice.Convict', 'Place'): {'GPE'}, ('Justice.Extradite', 'Origin'): {'GPE', 'FAC'}, ('Justice.Extradite', 'Destination'): {'GPE'}, ('Justice.Appeal', 'Place'): {'GPE', 'FAC'}, ('Business.Declare-Bankruptcy', 'Place'): {'GPE'}, ('Justice.Fine', 'Adjudicator'): {'PER'}, ('Life.Marry', 'Place'): {'GPE', 'FAC'}, ('Life.Divorce', 'Person'): {'PER'}, ('Personnel.Nominate', 'Agent'): {'ORG', 'GPE', 'PER'}, ('Business.Merge-Org', 'Org'): {'ORG'}, ('Justice.Acquit', 'Defendant'): {'PER'}, ('Justice.Sue', 'Adjudicator'): {'ORG', 'PER'}, ('Justice.Sue', 'Place'): {'GPE', 'LOC'}, ('Justice.Fine', 'Place'): {'GPE', 'FAC'}, ('Justice.Pardon', 'Place'): {'GPE'}, ('Justice.Pardon', 'Defendant'): {'PER'}, ('Justice.Acquit', 'Adjudicator'): {'PER'}, ('Transaction.Transfer-Money', 'Place'): {'GPE', 'LOC'}, ('Justice.Extradite', 'Agent'): {'ORG'}}